import "dotenv/config";
import { prisma } from "../src/lib/db";
import OpenAI from "openai";

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

async function main() {
    console.log("Starting to generate summaries for all events...");

    const events = await prisma.event.findMany({
        include: {
            universities: {
                include: { university: true }
            },
            registrations: {
                include: { registrant: true }
            }
        }
    });

    for (const event of events) {
        // Skip events already processed recently if needed, but we will overwrite.
        // Let's check if it has a description already generated by us? Let's just run.
        console.log(`Processing event: ${event.title} (${event.slug})...`);

        const totalRegistrations = event.registrations.length;
        const totalUniversities = event.universities.length;
        
        const countryMap = new Map<string, number>();
        const levelMap = new Map<string, number>();
        const majorsMap = new Map<string, number>();

        for (const reg of event.registrations) {
            const r = reg.registrant;
            if (r.country) countryMap.set(r.country, (countryMap.get(r.country) || 0) + 1);
            if (r.levelOfStudy) levelMap.set(r.levelOfStudy, (levelMap.get(r.levelOfStudy) || 0) + 1);
            if (r.interestedMajor) majorsMap.set(r.interestedMajor, (majorsMap.get(r.interestedMajor) || 0) + 1);
        }

        const topCountries = Array.from(countryMap.entries()).sort((a, b) => b[1] - a[1]).slice(0, 3).map(e => e[0]).join(", ");
        const topLevels = Array.from(levelMap.entries()).sort((a, b) => b[1] - a[1]).slice(0, 3).map(e => e[0]).join(", ");
        const topMajors = Array.from(majorsMap.entries()).sort((a, b) => b[1] - a[1]).slice(0, 3).map(e => e[0]).join(", ");
        const uniNames = event.universities.map(u => u.university.name).slice(0, 5).join(", ") + (totalUniversities > 5 ? ` and ${totalUniversities - 5} more` : "");

        const prompt = `
        You are an educational event marketer. Write a professional, engaging summary description for the following education fair event.
        
        Event Details:
        - Title: ${event.title}
        - Location: ${event.city || "Various"}, ${event.country || "Various"}
        - Date: ${new Date(event.startDateTime).toLocaleDateString()} to ${new Date(event.endDateTime).toLocaleDateString()}
        - Total Participating Universities: ${totalUniversities} (Including: ${uniNames})
        - Total Student Registrations: ${totalRegistrations}
        - Top Attendee Countries: ${topCountries || "N/A"}
        - Top Study Levels: ${topLevels || "N/A"}
        - Top Fields of Interest: ${topMajors || "N/A"}

        Write a 2-3 paragraph event summary. Make it sound like a successful, exciting event recap that highlights the scale, the participating universities, and the student demographics.
        Return the response as a JSON object with strictly these keys: 'en', 'tr', 'ar', 'ms'. Each key should contain the translated string.
        `;

        try {
            const completion = await openai.chat.completions.create({
                model: "gpt-4o-mini",
                messages: [{ role: "user", content: prompt }],
                response_format: { type: "json_object" }
            });

            const content = completion.choices[0].message.content;
            if (content) {
                const translations = JSON.parse(content);
                
                let existingTranslations: any = event.descriptionTranslations;
                if (typeof existingTranslations === "string") {
                    try { existingTranslations = JSON.parse(existingTranslations); } catch(e) { existingTranslations = {}; }
                }
                if (!existingTranslations || typeof existingTranslations !== "object") {
                    existingTranslations = {};
                }
                
                const updatedTranslations = {
                    ...existingTranslations,
                    en: translations.en || existingTranslations.en || event.description || "",
                    tr: translations.tr || existingTranslations.tr || "",
                    ar: translations.ar || existingTranslations.ar || "",
                    ms: translations.ms || existingTranslations.ms || "",
                };

                const engDescription = typeof translations.en === "string" ? translations.en : (typeof translations.summary === "string" ? translations.summary : String(translations.en || ""));

                await prisma.event.update({
                    where: { id: event.id },
                    data: {
                        description: engDescription,
                        descriptionTranslations: updatedTranslations
                    }
                });

                console.log(`✅ Successfully updated summaries for ${event.slug}`);
            }
        } catch (error: any) {
            console.error(`❌ Failed to generate summary for ${event.slug}:`, error.message || error);
        }
    }

    console.log("Done generating summaries.");
}

main()
    .catch(console.error)
    .finally(async () => await prisma.$disconnect());
